/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMultiSigWallet } from "./IMultiSigWallet";
export type { IRelayRecipient } from "./IRelayRecipient";
export type { IResolver } from "./IResolver";
