/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISETHCustom,
  ISETHCustomInterface,
} from "../../../../../contracts/interfaces/tokens/ISETH.sol/ISETHCustom";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "downgradeToETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradeByETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "upgradeByETHTo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISETHCustom__factory {
  static readonly abi = _abi;
  static createInterface(): ISETHCustomInterface {
    return new utils.Interface(_abi) as ISETHCustomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISETHCustom {
    return new Contract(address, _abi, signerOrProvider) as ISETHCustom;
  }
}
