/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sethSol from "./SETH.sol";
export type { sethSol };
export type { PureSuperToken } from "./PureSuperToken";
