/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomSuperTokenBaseMock } from "./CustomSuperTokenBaseMock";
export type { CustomSuperTokenMock } from "./CustomSuperTokenMock";
export type { CustomSuperTokenProxyMock } from "./CustomSuperTokenProxyMock";
