/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPureSuperToken__factory } from "./IPureSuperToken__factory";
export { IPureSuperTokenCustom__factory } from "./IPureSuperTokenCustom__factory";
