/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgreementBase } from "./AgreementBase";
export type { ConstantFlowAgreementV1 } from "./ConstantFlowAgreementV1";
export type { GeneralDistributionAgreementV1 } from "./GeneralDistributionAgreementV1";
export type { InstantDistributionAgreementV1 } from "./InstantDistributionAgreementV1";
