/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPureSuperTokenSol from "./IPureSuperToken.sol";
export type { iPureSuperTokenSol };
import type * as isethSol from "./ISETH.sol";
export type { isethSol };
export type { ERC20WithTokenInfo } from "./ERC20WithTokenInfo";
export type { TokenInfo } from "./TokenInfo";
