/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  SafeGasLibrary,
  SafeGasLibraryInterface,
} from "../../../contracts/libs/SafeGasLibrary";

const _abi = [
  {
    inputs: [],
    name: "OUT_OF_GAS",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bf2d083204337ca2fb1688e3be813907e7907a14aa3a6c9b210f4c2fda2e4bb964736f6c63430008130033";

type SafeGasLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SafeGasLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SafeGasLibrary__factory extends ContractFactory {
  constructor(...args: SafeGasLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SafeGasLibrary> {
    return super.deploy(overrides || {}) as Promise<SafeGasLibrary>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SafeGasLibrary {
    return super.attach(address) as SafeGasLibrary;
  }
  override connect(signer: Signer): SafeGasLibrary__factory {
    return super.connect(signer) as SafeGasLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SafeGasLibraryInterface {
    return new utils.Interface(_abi) as SafeGasLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeGasLibrary {
    return new Contract(address, _abi, signerOrProvider) as SafeGasLibrary;
  }
}
