/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as superfluidGovernanceIiSol from "./SuperfluidGovernanceII.sol";
export type { superfluidGovernanceIiSol };
export type { SuperfluidGovernanceBase } from "./SuperfluidGovernanceBase";
