/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SuperfluidGovernanceIIUpgradabilityTester__factory } from "./SuperfluidGovernanceIIUpgradabilityTester__factory";
