/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SuperfluidGovernanceII__factory } from "./SuperfluidGovernanceII__factory";
export { SuperfluidGovernanceIIProxy__factory } from "./SuperfluidGovernanceIIProxy__factory";
