/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITOGAv1 } from "./ITOGAv1";
export type { ITOGAv2 } from "./ITOGAv2";
export type { ITOGAv3 } from "./ITOGAv3";
export type { TOGA } from "./TOGA";
