/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SuperfluidGovernanceII } from "./SuperfluidGovernanceII";
export type { SuperfluidGovernanceIIProxy } from "./SuperfluidGovernanceIIProxy";
