/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as superfluidGovernanceIiSol from "./SuperfluidGovernanceII.sol";
export { SuperfluidGovernanceBase__factory } from "./SuperfluidGovernanceBase__factory";
